services:
  app:
    restart: always
    build: .
    ports:
      - 3000:3033
  mongo:
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - ambigu-data:/data/db
volumes:
 ambigu-data:
